# Generated by Django 3.2.21 on 2023-09-19 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderproduct',
            options={'ordering': ('-date_ordered',)},
        ),
        migrations.AlterModelOptions(
            name='shippingadress',
            options={'ordering': ('-order',)},
        ),
    ]
