# Generated by Django 3.2.21 on 2023-09-22 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20230922_0833'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingadress',
            old_name='state',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='shippingadress',
            old_name='zipcode',
            new_name='postcode',
        ),
        migrations.AddField(
            model_name='shippingadress',
            name='email',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='shippingadress',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='shippingadress',
            name='surname',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
