# Generated by Django 3.2.21 on 2023-10-26 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Videocall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calltype', models.CharField(choices=[('Material', 'Material'), ('Crochet', 'Crochet'), ('Knitting', 'Knitting'), ('Embroidery', 'Embroidery'), ('Cross-stitch', 'Cross-stitch')], default='Material', max_length=200)),
                ('booking_date', models.DateTimeField()),
                ('comment', models.TextField(default='Anything we should know?', max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='friendly_name',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
