# Generated by Django 3.2.21 on 2023-09-22 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_has_colors'),
    ]

    operations = [
        migrations.CreateModel(
            name='Videocall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calltype', models.CharField(choices=[('Material', 'Material'), ('Crochet', 'Crochet'), ('Knitting', 'Knitting'), ('Embroidery', 'Embroidery'), ('Cross-stitch', 'Cross-stitch')], default='Material', max_length=200)),
                ('booking_date', models.DateTimeField()),
                ('comment', models.TextField(default='Anything we should know?', max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='has_colors',
        ),
    ]
