# Generated by Django 3.2.21 on 2023-11-08 08:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_videocall_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocall',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
    ]
