# Generated by Django 3.2.21 on 2023-11-10 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20231109_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videocall',
            name='comment',
            field=models.TextField(max_length=500),
        ),
    ]
