# Generated by Django 3.2.21 on 2023-11-10 12:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_videocall_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videocall',
            name='user',
        ),
        migrations.AddField(
            model_name='videocall',
            name='created_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='videocall',
            name='booking_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
